spring:
  application:
    name: sp11_jwt_copy
  datasource:
    url: jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    genrate-ddl: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # Thymeleaf Cache Setting
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: d:/lec/00.share/98.temp/upload/
      max-request-size: 30MB
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: b1f1eae3af6105173debbb36df559484
            client-secret: 7dydRJ6fYQh9WstqDo21KreKXLBsrIyX
            scope: profile_nickname
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8090/login/oauth2/code/kakao
            client-name: kakao
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize

# Logging Setting
logging:
  level:
    org:
      hibernate: info
      springframework:
        security: info
    com:
      lec: debug

server:
  port: 8090
  servlet:
    encoding:
      force-response: true
      charset: utf-8

# file upload/download
path:
  upload: d:/lec/00.share/98.temp/upload/
  download: d:/lec/00.share/98.temp/download/

com:
  lec:
    upload:
      path: d:/lec/00.share/98.temp/upload/
    jwt:
      secret: hello1234567890
