spring:
  application:
    name: sp99_boot
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect				
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

