spring:
  application:
    name: sp12_axios
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    genrate-ddl: false      
    properties:
      hibernate:
        format_sql: true 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # Thymeleaf Cache Setting
  thymeleaf:
    cache: false

server:
  port: 8090

# Logging Setting
logging:
  level:
    org:
      hibernate: info

# file upload/download
path:
  upload: d:/lec/00.share/98.temp/upload/
  download: d:/lec/00.share/98.temp/download/